sources:
  - name: protofun_block_meta
    handler:
      graphql:
        endpoint: http://127.0.0.1:8000/subgraphs/name/protofun_block_meta

documents:
  - ./app/queries.gql

plugins:
  - pollingLive:
      defaultInterval: 1000
