sources:
  - name: protofun_block_meta
    handler:
      graphql:
        endpoint: http://api.protocol.fun/subgraphs/name/protofun_block_meta

documents:
  - ./app/queries.gql

plugins:
  - pollingLive:
      defaultInterval: 1000
